types:
  - build
  - build-image
  - test
  - promote
  - deploy

variables:
  APP_ENV: test


build:assets:
  image: node:6
  script:
    - npm set progress=false
    - npm install
    # - node_modules/.bin/bower install --allow-root
    - node_modules/.bin/gulp --production
  type: build
  tags:
    - docker
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
    - public/*

build:composer:
  image: composer/composer:1.1
  script:
    - composer install --no-autoloader --no-scripts --prefer-source --no-interaction
    - composer dump-autoload
    - php artisan clear-compiled
    - php artisan optimize
    - php artisan route:cache
  type: build
  tags:
    - docker
  cache:
    paths:
      - /root/.composer
  artifacts:
    paths:
    - vendor/*

build:image:
  image: docker:1.12
  variables:
    privileged: 'true'
    DOCKER_HOST: docker:2375
  services:
    - docker:1.12-dind
  script:
    - docker build --pull -t "registry.julus.uk/nasta/submissions:http-$CI_BUILD_REF" -f docker/http/Dockerfile .
    - docker build --pull -t "registry.julus.uk/nasta/submissions:cron-$CI_BUILD_REF" -f docker/cron/Dockerfile .
    - docker push "registry.julus.uk/nasta/submissions:http-$CI_BUILD_REF"
    - docker push "registry.julus.uk/nasta/submissions:cron-$CI_BUILD_REF"
  type: build-image
  tags:
    - docker
    - dind
  dependencies:
    - build:assets
    - build:composer

build-db:
  image: docker:1.12
  variables:
    privileged: 'true'
    DOCKER_HOST: docker:2375
  services:
    - docker:1.12-dind
  script:
    - docker build --pull -t "registry.julus.uk/nasta/test-db:$CI_BUILD_REF" docker/mysql
    - docker push "registry.julus.uk/nasta/test-db:$CI_BUILD_REF"
    - sleep 15
  type: build
  tags:
    - docker
    - dind

test:
  image: registry.julus.uk/nasta/submissions:http-$CI_BUILD_REF
  services:
    - registry.julus.uk/nasta/test-db:$CI_BUILD_REF
  script:
    - cd /src
    - cp storage/env.example storage/env
    - sed -i "s/DB_HOST=db/DB_HOST=registry.julus.uk-nasta-test-db/g" storage/env

    - php artisan key:generate
    - php artisan migrate --database=test_mysql
    - ./vendor/bin/phpunit
  type: test
  tags:
    - docker

promote:
  image: docker:1.12
  variables:
    privileged: 'true'
    DOCKER_HOST: docker:2375
  services:
    - docker:1.12-dind
  script:
    - docker pull "registry.julus.uk/nasta/submissions:http-$CI_BUILD_REF"
    - docker pull "registry.julus.uk/nasta/submissions:cron-$CI_BUILD_REF"
    - docker tag -f "registry.julus.uk/nasta/submissions:http-$CI_BUILD_REF" "registry.julus.uk/nasta/submissions:http-$CI_BUILD_REF_NAME"
    - docker tag -f "registry.julus.uk/nasta/submissions:cron-$CI_BUILD_REF" "registry.julus.uk/nasta/submissions:cron-$CI_BUILD_REF_NAME"
    - docker push "registry.julus.uk/nasta/submissions:http-$CI_BUILD_REF_NAME"
    - docker push "registry.julus.uk/nasta/submissions:cron-$CI_BUILD_REF_NAME"
  type: promote
  only:
    - master
    - develop
  tags:
    - docker
    - dind

deploy:
  image: registry.julus.uk/kubectl
  script:
    - kubectl --context=guild rolling-update "nasta-$CI_BUILD_REF_NAME" --image="registry.julus.uk/nasta/submissions:http-$CI_BUILD_REF"
  type: deploy
  only:
    - develop
    - master
  tags:
    - docker