types:
  - build
  - build-image
  - test
  - promote
  - deploy

variables:
  APP_ENV: test
  DOCKER_DRIVER: overlay2


build:assets:
  image: node:6
  script:
    - npm set progress=false
    - npm install
    # - node_modules/.bin/bower install --allow-root
    - node_modules/.bin/gulp --production
  type: build
  tags:
    - docker
  cache:
    paths:
      - node_modules
  artifacts:
    expire_in: 1 day
    paths:
    - public/*

build:composer:
  image: julusian/composer
  script:
    - composer install --no-autoloader --no-scripts --prefer-dist --no-interaction --no-dev
    - composer dump-autoload
    - php artisan clear-compiled
    - php artisan optimize
    - php artisan route:cache
  type: build
  tags:
    - docker
  cache:
    paths:
      - /root/.composer
  artifacts:
    expire_in: 1 day
    paths:
    - vendor/*

build:cron:
  image: docker:1.12
  variables:
    privileged: 'true'
    DOCKER_HOST: julusian-docker:2375
  services:
    - julusian/docker:1.12-dind
  script:
    - docker build --pull -t "registry.julus.uk/nasta-sub/cron:$CI_BUILD_REF" -f docker/cron/Dockerfile .
    - docker push "registry.julus.uk/nasta-sub/cron:$CI_BUILD_REF"
  type: build-image
  tags:
    - docker
    - dind-overlay
  dependencies:
    - build:assets
    - build:composer

build:http:
  image: docker:1.12
  variables:
    privileged: 'true'
    DOCKER_HOST: julusian-docker:2375
  services:
    - julusian/docker:1.12-dind
  script:
    - docker build --pull -t "registry.julus.uk/nasta-sub/http:$CI_BUILD_REF" -f docker/http/Dockerfile .
    - docker push "registry.julus.uk/nasta-sub/http:$CI_BUILD_REF"
  type: build-image
  tags:
    - docker
    - dind-overlay
  dependencies:
    - build:assets
    - build:composer

build:queue:
  image: docker:1.12
  variables:
    privileged: 'true'
    DOCKER_HOST: julusian-docker:2375
  services:
    - julusian/docker:1.12-dind
  script:
    - docker build --pull -t "registry.julus.uk/nasta-sub/queue:$CI_BUILD_REF" -f docker/queue/Dockerfile .
    - docker push "registry.julus.uk/nasta-sub/queue:$CI_BUILD_REF"
  type: build-image
  tags:
    - docker
    - dind-overlay
  dependencies:
    - build:assets
    - build:composer

build:db:
  image: docker:1.12
  variables:
    privileged: 'true'
    DOCKER_HOST: julusian-docker:2375
  services:
    - julusian/docker:1.12-dind
  script:
    - docker build --pull -t "registry.julus.uk/nasta/test-db:$CI_BUILD_REF" docker/mysql
    - docker push "registry.julus.uk/nasta/test-db:$CI_BUILD_REF"
  type: build-image
  tags:
    - docker
    - dind-overlay
  dependencies: []

test:
  image: registry.julus.uk/nasta-sub/http:$CI_BUILD_REF
  services:
    - registry.julus.uk/nasta/test-db:$CI_BUILD_REF
    - mailhog/mailhog
  script:
    - cd /src
    - cp storage/env.example storage/env
    - sed -i "s/DB_HOST=db/DB_HOST=registry.julus.uk-nasta-test-db/g" storage/env
    - sed -i "s/mailhog/mailhog-mailhog/g" storage/env

    - composer install --no-scripts --prefer-dist --no-interaction --dev

    - php artisan key:generate
    - php artisan migrate --database=test_mysql
    - DB_CONNECTION=test_mysql APP_DEBUG=false APP_ENV=test ./vendor/bin/phpunit
  type: test
  tags:
    - docker
  dependencies: []

promote:
  image: docker:1.12
  variables:
    privileged: 'true'
    DOCKER_HOST: julusian-docker:2375
  services:
    - julusian/docker:1.12-dind
  script:
    - docker pull "registry.julus.uk/nasta-sub/http:$CI_BUILD_REF"
    - docker pull "registry.julus.uk/nasta-sub/cron:$CI_BUILD_REF"
    - docker pull "registry.julus.uk/nasta-sub/queue:$CI_BUILD_REF"

    - docker tag "registry.julus.uk/nasta-sub/http:$CI_BUILD_REF" "registry.julus.uk/nasta-sub/http:$CI_BUILD_REF_NAME"
    - docker tag "registry.julus.uk/nasta-sub/cron:$CI_BUILD_REF" "registry.julus.uk/nasta-sub/cron:$CI_BUILD_REF_NAME"
    - docker tag "registry.julus.uk/nasta-sub/queue:$CI_BUILD_REF" "registry.julus.uk/nasta-sub/queue:$CI_BUILD_REF_NAME"

    - docker push "registry.julus.uk/nasta-sub/http:$CI_BUILD_REF_NAME"
    - docker push "registry.julus.uk/nasta-sub/cron:$CI_BUILD_REF_NAME"
    - docker push "registry.julus.uk/nasta-sub/queue:$CI_BUILD_REF_NAME"
  type: promote
  only:
    - master
    - develop
  tags:
    - guild
    - docker
    - dind-overlay
  dependencies: []

deploy:
  image: registry.julus.uk/kubectl
  script:
    - sed -i 's/:latest/:'$CI_BUILD_REF'/g' kubernetes/deployment.yaml
    - kubectl --context=guild --namespace=nasta apply -f kubernetes/deployment.yaml
  type: deploy
  only:
    - develop
    - master
  tags:
    - docker
  dependencies: []