apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: sub-http
    name: sub-http
  spec:
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          name: sub-http
      spec:
        containers:
        - image: eu.gcr.io/nasta-2017/sub-http:latest
          name: sub-http
          livenessProbe:
            httpGet:
              path: /login
              timeoutSeconds: 5
              periodSeconds: 10
              initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /login
              timeoutSeconds: 5
              periodSeconds: 10
              initialDelaySeconds: 30
          env:
            - name: VM_ENV
              value: production
            - name: APP_ENV
              value: production
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /src/storage
              name: storage
        volumes:
        - name: storage
          configMap:
            name: nasta-sub
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: sub-cron
    name: sub-cron
  spec:
    replicas: 1
    strategy:
      rollingUpdate:
        maxSurge: 0
      type: RollingUpdate
    template:
      metadata:
        labels:
          name: sub-cron
      spec:
        containers:
        - image: eu.gcr.io/nasta-2017/sub-cron:latest
          name: sub-cron
          env:
            - name: VM_ENV
              value: production
            - name: APP_ENV
              value: production
          volumeMounts:
            - mountPath: /src/storage
              name: storage
        volumes:
        - name: storage
          configMap:
            name: nasta-sub
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: sub-queue
    name: sub-queue
  spec:
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          name: sub-queue
      spec:
        containers:
        - image: eu.gcr.io/nasta-2017/sub-queue:latest
          name: sub-queue
          command: ["/start.sh"]
          args: ["--timeout=10", "--tries=3", "--delay=10"]
          env:
            - name: VM_ENV
              value: production
            - name: APP_ENV
              value: production
          volumeMounts:
            - mountPath: /src/storage
              name: storage
        volumes:
        - name: storage
          configMap:
            name: nasta-sub