apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      name: sub-mailhog
    name: sub-mailhog
    namespace: nasta
  spec:
    replicas: 1
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          name: sub-mailhog
      spec:
        containers:
        - image: mailhog/mailhog
          name: sub-mailhog
          ports:
            - containerPort: 8025
              protocol: TCP
            - containerPort: 1025
              protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    name: sub-mailhog
    namespace: nasta
  spec:
    ports:
      - name: http
        port: 8025 # the port that this service should serve on
        targetPort: 8025
        nodePort: 0
        protocol: TCP
      - name: smtp
        port: 1025 # the port that this service should serve on
        targetPort: 1025
        nodePort: 0
        protocol: TCP

    # just like the selector in the replication controller,
    # but this time it identifies the set of pods to load balance
    # traffic to.
    selector:
      name: sub-mailhog
    type: NodePort