apiVersion: v1
kind: Service
metadata:
  name: sub-http
spec:
  ports:
    - name: http
      port: 80 # the port that this service should serve on
      targetPort: 80
      protocol: TCP

  # just like the selector in the replication controller,
  # but this time it identifies the set of pods to load balance
  # traffic to.
  selector:
    name: sub-http
  type: ClusterIP